### ISSUE TITLE
Circular import problem when using es6-module-loader

### ISSUE THREAD

**Issue by frankier** [jspm/nodelibs-stream#1]
This line: https://github.com/iojs/readable-stream/blob/214a7eb1719b524e78c7634eaee6bd408e6c532f/lib/_stream_readable.js#L44 causes Stream.prototype to be referenced before it's available.

Not sure what the best path is here. I assume with Browserify Stream.prototype already references the correct object here so I guess this is due to intended semantic differences between Browserify and es6 modules?

Use case: trying to get request/request working, but this actually seems to cause a browser traceback even with a simple "import Stream from 'stream'".

Full traceback: https://gist.github.com/frankier/f7c2e4fa12dbecb0e682

**Comment by guybedford** [comment]
Yes this is a common issue. Circular references are actually supported fine. The specific issue here is the fact that jspm uses an indirection module:

`require('stream')` -> `jspm_packages/npm/stream@x.y.z.js` -> `jspm_packages/npm/stream@x.y.z/stream.js`

(something like that)

The indirection module looks like `module.exports = require('stream@x.y.z/stream')`.

That single module then messes with the circular reference behaviours.

The way to fix this is to alter the module that is requiring stream in the first place, to directly request the main (`require('stream/index')` over `require('stream')`). This is setup in the overrides for packages that have this issue. See for example https://github.com/jspm/registry/blob/master/package-overrides/npm/readable-stream%401.1.13.json.

If you can track this down tot he map config that is needed to fix the package using stream in your case we can add an override to fix it.

In terms of the root cause, this is a definite consideration as the architecture evolves.
